### ISSUE TITLE
Attribute values change after reload when their values are serialized objects in JSON format

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#31] opened 2017-07-20 13:39 UTC
*hikaru.cs.au.dk*
When serializing a JavaScript object and storing it in an element attribute, the double quotes `"` of a serialized JavaScript object are replaced by single quotes `'` after a page reload.

*webstrates.cs.au.dk*
Serializing a JavaScript object into an element attribute correctly retains the double quotes `"` even after a page reload.

*Steps to reproduce*
Go to: [https://hikaru.cs.au.dk/new](https://hikaru.cs.au.dk/new) and execute the following JavaScript code in the console.

```
document.body.setAttribute("test", JSON.stringify({ a: "a", b: "b", c: 1 }));
```

It will add an attribute `test` to the `body` element with the value `{"a":"a","b":"b","c":1}`, which is a valid JSON format. But it will be `{'a':'a','b':'b','c':1}` after page reload (invalid JSON format).

**Comment by kbadk** [comment] 2017-07-20 14:46
Seems to have been caused by a slip up when adding webpack to the project, because we then converted all string quotations from `"`'s to `'`'s. It's been fixed now, though!

**Closed by kbadk** 2017-07-20 14:46 UTC
