### ISSUE TITLE
Scripts are executed async, which isn't conform with the default loading and execution behavior

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#10] opened 2016-08-21 15:55 UTC
> Scripts that are dynamically created and added to the document are async by default, they don’t block rendering and execute as soon as they download, meaning they could come out in the wrong order.

[http://www.html5rocks.com/en/tutorials/speed/script-loading/](http://www.html5rocks.com/en/tutorials/speed/script-loading/)

This can cause script error when using Webstrates. For example, bootstrap 3 depends on jQuery but since dynamically added scripts are executed async it might happen that bootstrap is executed before jQuery has finished loading.

Adding `script.async = false;` as default behavior would confirm with browsers' default loading and execution behavior.

**Comment by raedle** [comment] 2016-08-21 18:22
Adding the following code to jqml.js partially solves the issue.

```javascript
if (xmlNs) {
    selector = document.createElementNS(xmlNs, name);
} else {
    selector = document.createElement(name);
};

// === BEGIN ADD ===
// https://github.com/Webstrates/Webstrates/issues/10
// Scripts that are dynamically created and added to the document are async by default, they don't
// block rendering and execute as soon as they download, meaning they could come out in the wrong
// order. http://www.html5rocks.com/en/tutorials/speed/script-loading/
//
// This can cause script error when using Webstrates. For example, bootstrap 3 depends on jQuery but
// since dynamically added scripts are executed async it might happen that bootstrap is executed before
// jQuery has finished loading. Adding script.async = false; as default behavior would confirm with
// browsers' default loading and execution behavior.
if (selector.tagName === 'SCRIPT') {
    selector.async = false;
}
// === END ADD ===
```

External scripts are executed in proper order then. However, inline scripts are still executed immediately. The following document will result in an error because $ (jQuery) might not be loaded on execution of the inline script.

```html
<html>
  <head>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript">
      $(function() { } // ERROR: jQuery $ not yet available
    </script>
  </head>
  <body>
  </body>
</html>
```

**Comment by kbadk** [comment] 2016-08-21 18:37
With your fix, your example works for me (sans the missing closing parenthesis). It'd also be odd if `async` only worked on _some_ `<script>` tags. Are you able to consistently reproduce?

**Comment by raedle** [comment] 2016-08-21 18:51
It doesn't work with my fork because I removed the jQuery 1.7.2 dependency entirely. In the main repos it loads that jQuery dependency before the 'new' external script kicks in. What does it print in the console when you load the following document?

```html
<html><head>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript">
      console.log($().jquery); // It prints "1.7.2" but it should be "3.1.0" when loaded properly.
    </script>
  </head>
  <body>
  
  </body>
</html>
```

**Comment by kbadk** [comment] 2016-08-21 18:54
You're right. That does indeed print 1.7.2.

**Closed** 2017-04-06 14:07 UTC
Labels: bug
